### ISSUE TITLE
Completer doesn't close when the field is cleared

### ISSUE THREAD

**Issue by szh** [oferh/ng2-completer#194] opened 2017-04-07 16:32 UTC
When I start typing in an ng2-completer, the suggestion list opens, but when I clear all the text from the field, it stays open. I'm not sure if this is a feature or a bug.
I created a workaround for now:
`<ng2-completer #completer [(ngModel)]="value" (ngModelChange)="valChanged($event, completer)">`
`function valChanged(val, completer) { if (!val) completer.close() }`

**Comment by oferh** [comment] 2017-04-09 09:02
@szh this is by design.
There is issue #189 that suggests closing the dropdown if there are no results.

**Comment by oferh** [comment] 2017-04-17 14:27
it should close however when using `minSearchLength` and the length is less than the minimum

**Closed** 2017-04-22 09:08 UTC
Labels: bug
