### ISSUE TITLE
Error Module not already loaded loading "@angular/core"

### ISSUE THREAD

**Issue by josepoma** [oferh/ng2-completer#16] opened 2016-08-03 16:30 UTC
I did all steps to implement the component, but when running I get this:

localhost/:148 Error: Error: Module not already loaded loading "@angular/core" as http://localhost:5555/node_modules/@angular/core/bundles/core.umd.
	    at Object.eval (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:76:19)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at Object.c (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:371:15)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at Object.eval (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:58:24)
	    at __webpack_require__ (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:30:30)
	    at eval (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:50:18)
	    at eval (http://localhost:5555/node_modules/ng2-completer/bundles/ng2-completer.js:53:10)
	    at Object.eval (http://localhost:5555/app/dashboard/tdr/tdr-list.component.js:14:23)
	    at eval (http://localhost:5555/app/dashboard/tdr/tdr-list.component.js:65:4)
	    at eval (http://localhost:5555/app/dashboard/tdr/tdr-list.component.js:66:3)
	    at Object.eval (http://localhost:5555/app/dashboard/tdr/index.js:5:10)
	    at eval (http://localhost:5555/app/dashboard/tdr/index.js:10:4)
	    at eval (http://localhost:5555/app/dashboard/tdr/index.js:11:3)
	    at Object.eval (http://localhost:5555/app/dashboard/dashboard.routes.js:17:16)
	    at eval (http://localhost:5555/app/dashboard/dashboard.routes.js:29:4)
	    at eval (http://localhost:5555/app/dashboard/dashboard.routes.js:30:3)
	    at Object.eval (http://localhost:5555/app/dashboard/index.js:6:10)
	    at eval (http://localhost:5555/app/dashboard/index.js:10:4)
	    at eval (http://localhost:5555/app/dashboard/index.js:11:3)
	    at Object.eval (http://localhost:5555/app/app.routes.js:4:15)
	    at eval (http://localhost:5555/app/app.routes.js:16:4)
	    at eval (http://localhost:5555/app/app.routes.js:17:3)
	    at Object.eval (http://localhost:5555/app/main.js:7:20)
	    at eval (http://localhost:5555/app/main.js:28:4)
	    at eval (http://localhost:5555/app/main.js:29:3)
	Evaluating http://localhost:5555/app/dashboard/tdr/tdr-list.component.js
	Evaluating http://localhost:5555/app/dashboard/tdr/index.js
	Evaluating http://localhost:5555/app/dashboard/dashboard.routes.js
	Evaluating http://localhost:5555/app/dashboard/index.js
	Evaluating http://localhost:5555/app/app.routes.js
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js

**Comment by oferh** [comment] 2016-08-03 20:32
@josepoma can you add your system.js config?

**Comment by josepoma** [comment] 2016-08-03 21:23
@oferh Here the system.js config :

System.config({
  defaultJSExtensions: true, 
  map: {
    'rxjs'                  : 'node_modules/rxjs',
    'lodash'                : 'node_modules/lodash/lodash.js',
    '@angular'              : 'node_modules/@angular',
    'ng2-pagination'        : 'node_modules/ng2-pagination',
    'ng2-slim-loading-bar'  : 'node_modules/ng2-slim-loading-bar',        
    'ng2-datetime'          : 'node_modules/ng2-datetime/',
    'ng2-bs4-modal'         : 'node_modules/ng2-bs4-modal',
    'auto-complete'         : 'node_modules/ng2-auto-complete/dist/index.js',
    'datetime-picker'       : 'node_modules/ng2-datetime-picker/dist/index.js',
    '@vaadin'               : 'node_modules/@vaadin',
    'ng2-completer'         : 'node_modules/ng2-completer/bundles'
  },
  packages: {
    '@angular/core': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/compiler': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/common': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/http': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/platform-browser': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/platform-browser-dynamic': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    '@angular/router': {
      main: 'index.js',
      defaultExtension: 'js'
    },
    'rxjs': {
      defaultExtension: 'js'
    },
    'lodash/lodash' :{   
      main: 'lodash.js',    
      defaultExtension: 'js'
    },
    'ng2-pagination' :{
      defaultExtension: 'js'
    }
    ,'ng2-slim-loading-bar' : {
      defaultExtension: 'js'
    }
    ,'ng2-datetime': { 
      main: 'index.js', 
      defaultExtension: 'js' 
    }
    ,'auto-complete': { 
      main: 'index.js', 
      defaultExtension: 'js' 
    }
    ,'datetime-picker': { 
      main: 'index.js', 
      defaultExtension: 'js' 
    }
    ,'@vaadin/angular2-polymer': { 
      main: 'index.js' }
    ,'ng2-completer': {
       main: 'ng2-completer.js', 
       format: 'cjs' }
  }
});

Thanks for your answer.

**Comment by oferh** [comment] 2016-08-03 21:34
try loading `ng2-completer` with:

```
map = {
  'ng2-completer': 'node_modules/ng2-completer/bundles/ng2-completer.js'
}

packages = {
  'ng2-completer': {
       format: 'cjs'
  }
}
```

**Comment by josepoma** [comment] 2016-08-03 21:55
Do what you said, but get the same error. 
![geterror](https://cloud.githubusercontent.com/assets/12588269/17383331/04ec880e-599b-11e6-9f56-85e6f4d75087.png)

**Comment by oferh** [comment] 2016-08-04 05:04
@josepoma it looks like System.js ignores `format: 'cjs'`  for some reason. If you can I think it'll be better to ask the question in system.js issues.

**Comment by mickeychu** [comment] 2016-08-08 11:37
I have the same problem

**Comment by oferh** [comment] 2016-08-08 16:41
@mickeychu can you provide a sample?

**Comment by oferh** [comment] 2016-10-04 05:18
Closing the issue because it's not reproducible.

**Closed by oferh** 2016-10-04 05:18 UTC

**Comment by Handavipul** [comment] 2017-08-31 09:20
Hi @oferh @josepoma 
I am  facing (SystemJS) Module not already loaded loading "@angular/core" as http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js.↵	Error: Module not already loaded loading "@angular/core" as http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js.↵	    at Object.eval (http://localhost:3000/node_modules/lib/shell.umd.js:94:18) [<root>]↵

**Comment by oferh** [comment] 2017-08-31 09:24
Hi @Handavipul,

Can you provide a plunker or a repo that reproduces it?

**Comment by viv32ek** [comment] 2018-01-03 06:45
I am facing a similar issue.. did you find a dolution fot it?
