### ISSUE TITLE
autoHighlight should allow backspace key

### ISSUE THREAD

**Issue by yagilofir** [oferh/ng2-completer#273] opened 2017-07-08 15:47 UTC
Hi.
First, thanks a lot for this wonderful component.
I'm trying to use the "autoHighlight" feature. My list has 3 items with the letter "d":

Dni
Wind
Clouds

Now, as soon as I press "d", the search box text is auto completed to "Dni". Now, if I regret and I press backspace, the "Dni" in the text box refuses to get deleted (no metter how many times I press backspace).
Can you please fix this ? I believe that the first option in the list should be highlighted in this case (so if I press enter, it will choose the first option) and the text box should show "Dni" and highlight the "ni" text, so the user can keep writing letters (the user might want to write the letter "n" after he writes "d"... and this is currently not possible (he gets "Dni**n**") ). 
My suggestion is actually inspired from Google Chrome address bar behavior.

Thanks.

**Comment by oferh** [comment] 2017-07-11 18:45
duplicate of #261

**Closed** 2017-07-11 18:45 UTC
Labels: duplicate
