### ISSUE TITLE
Error when using CustomData

### ISSUE THREAD

**Issue by arthurfrancioni** [oferh/ng2-completer#290] opened 2017-08-02 18:20 UTC
It works fine but Visual Studio code is showing this error

Versions:
    "angular/animations": "^4.1.2",
    "angular/common": "^4.0.0",
    "angular/compiler": "^4.0.0",
    "angular/core": "^4.0.0",
    "angular/forms": "^4.0.0",
    "angular/http": "^4.0.0",
    "angular/platform-browser": "^4.0.0",
    "angular/platform-browser-dynamic": "^4.0.0",
    "angular/router": "^4.0.0",
    "rxjs": "^5.1.0"

[ts]
Class 'CustomData' incorrectly implements interface 'CompleterData'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<CompleterItem[], R>) => Observable<CompleterItem[]>' is not assignable to type '<R>(operator: Operator<CompleterItem[], R>) => Observable<R>'.
      Type 'Observable<CompleterItem[]>' is not assignable to type 'Observable<R>'.
        Type 'CompleterItem[]' is not assignable to type 'R'.

![untitled-1 fw](https://user-images.githubusercontent.com/1223383/28888193-1a525f56-7796-11e7-9d24-f2ff52d54963.png)

Can someone help me?

**Comment by oferh** [comment] 2017-08-05 06:50
duplicate of #268

**Closed by oferh** 2017-08-05 06:50 UTC
