### ISSUE TITLE
would like to be able to set withCredentials=true for remote datasource

### ISSUE THREAD

**Issue by PhilipNunn** [oferh/ng2-completer#198] opened 2017-04-17 19:59 UTC
Prevents accessing secured http endpoints.
Getting the results manually and using a local datasource works but presents some potential timing issues. i.e. [pause] must be set to a time where the results are certain to be back instead of updating as soon as they are available.

**Comment by oferh** [comment] 2017-04-17 21:50
duplicate of #71

**Closed** 2017-04-23 05:53 UTC
