### ISSUE TITLE
Support HttpClient and Interceptors

### ISSUE THREAD

**Issue by vandensd** [oferh/ng2-completer#314] opened 2017-09-11 04:22 UTC
Not exactly sure if it is this simple but if you could change to use new HttpClient class (old http deprecated in Angular 5) then I believe that interceptors can be used and requestOptions is not necessary.  I'm using interceptors for auth headers and it would be nice that it just worked.

**Comment by oferh** [comment] 2017-09-12 16:43
duplicate of #296

**Closed by oferh** 2017-09-12 16:43 UTC
