### ISSUE TITLE
Please allow me to add PR to fix #442

### ISSUE THREAD

**Issue by MrNocTV** [oferh/ng2-completer#452] opened 2020-03-24 17:37 UTC
I have working solution for #442 
I have traced down the root causes:

1. The code is not correctly loading the `completer` in `CompleterCmp`. Please check [this ](https://stackoverflow.com/questions/36345618/get-reference-to-a-directive-used-in-a-component) for more info.
2. Putting the code to subscribe on `completer` in `ngOnInit` doesn't work, we have to put it in `ngAfterViewInit`

Can I be added as a contributor so that I can make a PR?

Thank you in advance.

**Comment by stanislas** [comment] 2020-03-27 20:12
@MrNocTV I stumbled upon the same problem. Thank you for tracing down the root causes. 
Could you publish your fix on your fork? That would be of great help.

**Comment by greywire** [comment] 2020-03-28 02:53
Definitely second this! Its preventing my company releasing our angular 8 upgraded app...

**Comment by MrNocTV** [comment] 2020-03-28 14:38
@stanislas I have created a PR for it. You can take a look [here](https://github.com/oferh/ng2-completer/pull/453).

**Comment by osterland** [comment] 2020-04-01 15:43
@MrNocTV
 any Idea why i get in all my .ts imports "Cannot find module 'ng2-completer'", when i try to use youre PR with npm install oferh/ng2-completer#pull/453/head --save ? 

TY!

**Comment by greywire** [comment] 2020-04-01 17:24
> @MrNocTV
> any Idea why i get in all my .ts imports "**Cannot find module 'ng2-completer**'", when i try to use youre PR with **npm install oferh/ng2-completer#pull/453/head --save** ?
> 
> TY!

Yeah I'm getting the same thing...

**Comment by osterland** [comment] 2020-04-02 11:57
@greywire 

looks like u are in a little time pressure - if u want a quick fix ( like me ) do the following: 
1) go to your node modules and find die ng2-completer 
2) ( and thats now a little different from the PR ) u need to edit the 2 files ng2-completer.js in esm5 and in esm2015 ( probably the one thtat matchs ur ts would be enough ? ) 
3) in these two files u basically do what @MrNocTV did in his PR (in the completer move the stuff from the ngOnInit()  in the ( alrdy existing) ngAfterViewInit() 

downside is u have to do this after every npm i - until the package is fixed

hope it helps!

**Comment by lizelleboshoff** [comment] 2020-04-08 09:12
Can we please get this merged?  I'ts preventing us from upgrading to Angular 9.
Thank you.

**Comment by oferh** [comment] 2020-04-09 02:59
@MrNocTV merged the PR thank you for the contribution!

**Closed by oferh** 2020-04-09 02:59 UTC
