### ISSUE TITLE
can't set css class

### ISSUE THREAD

**Issue by pablo28jg** [oferh/ng2-completer#62] opened 2016-10-12 02:55 UTC
can't set css class

**Comment by MrJuliuss** [comment] 2016-10-12 07:17
Hi, same issue, styles seems to be reset.

**Comment by oferh** [comment] 2016-10-12 19:20
@pablo28jg @MrJuliuss can you add sample code?

**Comment by kamran-pervaiz** [comment] 2016-10-21 10:37
I have the same issue, I added a home component and a custom data

<ng2-completer [(ngModel)]="searchStr" [dataService]="customData" [minSearchLength]="3" [placeholder]="'search for factory'"
                   [textSearching]="'Please wait...'" (selected)="onSelected($event)"></ng2-completer> 

http://stackoverflow.com/questions/40172248/angular-2-ng2-completer-avoid-http-dependency-injection-in-service-from-compo

When i override it in my home.component.css, it does not override for some odd reason. any idea?

```
.completer-input {
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
}
```

**Comment by oferh** [comment] 2016-10-28 11:23
This is probably due to angular's [view encapsulation](http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html) please try :

```
/deep/ .completer-input  {
display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075);
    -webkit-transition: border-color ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
}
```

**Comment by gelliott181** [comment] 2016-10-28 15:57
Please check out [shadow piercing CSS](https://drafts.csswg.org/css-scoping/#deep-combinator). This will allow you to get around view encapsulation.

**Comment by Rudde** [comment] 2016-11-24 11:24
@oferh How could I use /deep/ on css frameworks such as bootstrap? I would like it to use the "form-control" class to get the bootstrap look and feel, but it seems problematic to add this class to the directive? :S

**Comment by oferh** [comment] 2016-12-04 21:23
At the moment if you want to apply bootstrap styles I'd recommend that you create a custom component like the one created for [material design](https://github.com/oferh/ng2-completer/blob/master/demo/material-cmp.ts)

**Comment by oferh** [comment] 2016-12-23 10:43
duplicate of #40

**Closed by oferh** 2016-12-23 10:43 UTC

**Comment by grenager** [comment] 2017-02-14 00:11
I had the same problem, would you please add a note in the documentation about view encapsulation problem and how to get around it? This is not obvious to someone who wants to use your directive in their project and wants to style it using the component-level CSS. Thank you.

**Comment by oferh** [comment] 2017-02-14 08:32
I'll try to set the view encapsulation of the component to null and test it might be the best option as it seems like this issue is very common.

**Comment by oferh** [comment] 2017-03-12 10:53
view encapsulation will be checked as part of #164
